modLoader = "javafml"
loaderVersion = "${forge_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    authors = "${mod_author}"
    description = '''${mod_description}'''
    logoFile = "icon_forge.png"

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "resourcelibrary"
    mandatory = true
    versionRange = "*"
    ordering = "NONE"
    side = "BOTH"
