org.gradle.jvmargs=-Xmx8192M
org.gradle.deamon=false

# Project
version=2.4.0
group=net.xstopho.resource_nether_ores
java_version=21
modrinth_id=GXPQteCw
curseforge_id=1009367

# Common
mod_name=Resource Nether Ores
mod_author=xStopho
mod_id=resource_nether_ores
mod_license=MIT
mod_credits=
mod_description=Add Vanilla Ores to the Nether Dimension

# Dependencies
resource_library=2.9.1