org.gradle.jvmargs=-Xmx8192M
org.gradle.daemon=false

version=3.1.0
group=net.morthen
java_version=25

modrinth_id=GXPQteCw
curseforge_id=1009367

# Common
minecraft_version=26.1.2

mod_id=resource_nether_ores
mod_name=Resource Nether Ores
mod_author=Morthen
mod_license=MIT
mod_description=Add Vanilla Ores to the Nether Dimension

neoform=26.1.2-1
neoforge=26.1.2.71
fabric_api=0.155.2+26.1.2
fabric_loader=0.19.3
forge=64.1.0

resourcelibrary=26.1.2-4.0.3

# Additional stuff
sources_url=https://github.com/Morthen-Mods/Resource-Nether-Ores
issues_url=https://github.com/Morthen-Mods/Resource-Nether-Ores/issues