plugins {
    id 'loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge

    def at = file('../common/src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) accessTransformers = [at]

    runs {
        configureEach {
            systemProperty('neoforge.enableGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
            gameDirectory = file("../fabric/runs/${it.name.toLowerCase()}")
        }
    }
    mods {
        "${mod_id}" { sourceSet sourceSets.main }
    }
}

publishMods {
    file = jar.archiveFile
    modLoaders.addAll("neoforge")
}