modLoader = "javafml"
loaderVersion = "[2,)"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    authors = "${mod_author}"
    description = '''${mod_description}'''
    logoFile = "logo_forge.png"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    required = true
    versionRange = "[26.1, ${neoforge}]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    required = true
    versionRange = "[26.1, ${minecraft_version}]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "resourcelibrary"
    type = "required"
    versionRange = "[${minecraft_version}-${resource_library},)"
    ordering = "AFTER"
    side = "BOTH"