modLoader = "javafml"
loaderVersion = "${neoforge_loader_version}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    authors = "${mod_author}"
    description = '''${mod_description}'''
    logoFile = "logo_forge.png"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    required = true
    versionRange = "${neoforge_loader_version}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    required = true
    versionRange = "[1.20.4, 1.20.5)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "resourcelibrary"
    required = true
    versionRange = "*"
    ordering = "NONE"
    side = "BOTH"