modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    authors = "${mod_author}"
    description = '''${mod_description}'''
    logoFile = "icon.png"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    required = true
    versionRange = "${neoforge_loader_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    required = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "resourceconfigapi"
    required = true
    versionRange = "[${resource_config_api},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "resourcelibrary"
    required = true
    versionRange = "[${resource_library},)"
    ordering = "NONE"
    side = "BOTH"