plugins {
    id 'ml-loader'
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin'
}

dependencies {
    implementation "net.xstopho.resourcelibrary:resourcelibrary-neoforge:${resource_library}"
}

neoForge {
    version = neoforge_version

    parchment {
        minecraftVersion = parchment_mc_version
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enableGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
            gameDirectory = file("../common/runs/${it.name.toLowerCase()}")
        }
        client {
            client()
        }
        server {
            server()
            programArguments.add('nogui')
        }
        data {
            clientData()
            programArguments = ['--mod', project.mod_id, '--all', '--output', file('src/generated/').getAbsolutePath(), '--existing', file('../common/src/main/resources/').getAbsolutePath()]
        }
    }
    mods {
        "${mod_id}" { sourceSet sourceSets.main }
    }
}

publishMods {
    file = jar.archiveFile
    modLoaders.add("neoforge")
}